<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <AssemblyName>SubSteward.Plugin</AssemblyName>
    <RootNamespace>SubSteward.Plugin</RootNamespace>
    <Version>0.1.0</Version>
    <AssemblyVersion>0.1.0.0</AssemblyVersion>
    <FileVersion>0.1.0.0</FileVersion>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MediaBrowser.Server.Core" Version="4.9.1.90" />
  </ItemGroup>
</Project>
